name: Terraform Apply
on:
  push:
    branches:
      - master
    paths:
      - 'deployments/*.tf'
      - '.github/workflows/terraform*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        folders:
          - deployments/
    steps:
    - uses: actions/checkout@master
    - name: Setup SSH
      uses: ./.github/actions/bin/sh
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        args: '"
              mkdir -p $HOME/.ssh;
              echo \"$SSH_PRIVATE_KEY\" > $HOME/.ssh/id_rsa;
              chmod 400 $HOME/.ssh/id_rsa;
              "'
    - name: terraform-init
      uses: hashicorp/terraform-github-actions@v0.6.3
      with:
        tf_actions_version: 0.12.18
        tf_actions_working_dir: ${{ matrix.folders }}
        tf_actions_subcommand: 'init'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/id_rsa"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: terraform-apply
      uses: ./.github/actions/terraform/apply
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: ${{ matrix.folders }}
      with:
        args: '-lock-timeout=30m'
    - name: Generate helm auth configuration
      uses: ./.github/actions/generate_auth_config
      id: gen_config
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TERRAFORM_PATH: ${{ matrix.folders }}
    - name: Shell
      if: steps.gen_config.outputs.do_create_issue == 1
      uses: ./.github/actions/bin/sh
      with:
        args: '"cat .github/helm_auth.md ${GITHUB_WORKSPACE}/auth_config_issue.md > ${GITHUB_WORKSPACE}/issue.md"'
    - name: Shell
      if: steps.gen_config.outputs.do_create_issue == 1
      uses: ./.github/actions/bin/sh
      with:
        args: '"sed -e \"s/{{ ACTOR }}/${GITHUB_ACTOR}/\" -i ${GITHUB_WORKSPACE}/issue.md"'
    - uses: JasonEtco/create-an-issue@v2.0.0
      if: steps.gen_config.outputs.do_create_issue == 1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: issue.md
